### ISSUE TITLE
oci create cluster behind proxy not use parameter

### ISSUE THREAD

**Issue by chris93111** [rancher-plugins/kontainer-engine-driver-oke#21]
Hi

rancher 2.4.8 , driver 1.15.0

The driver don't user proxy parameter set in rancher
all work aws/helm/download drivers with proxy
only oci doesn't work

i have try also rancher with directly internet and it's work with same account

Get "https://iaas.XXXXXX.oraclecloud.com/XXXXXXX/vcns?compartmentId=XXXXXXXXXdisplayName=XXXXX": dial tcp XXXXXXX:443: i/o timeout

**Comment by jlamillan** [comment]
Thanks for the report, we'll take a look. ￼

**Comment by jlamillan** [comment]
Which proxy environment variables are you setting on the Rancher server?

**Comment by jlamillan** [comment]
@chris93111 I've verified that when `HTTP_PROXY` and `HTTPS_PROXY` environment variables are present in the environment, the OKE driver (`v1.5.0`) will use the proxy. This is because to OCI SDK does not set the `http.Transport`, and the default implementation will pick up `http.ProxyFromEnvironment` by default - at least that's the way it's working with the SDK version being used in `v1.5.0` of the driver.

I'm going to check with the folks at Rancher to confirm whether Rancher server / kontainerdriver are ensuring the environment variables are being passed into a non-built-in driver like OKE assuming they are set on the server i.e. 

```yaml
  containers:
  - name: rancher
    image: rancher/rancher:v2.4.9
    env:
    - name: HTTP_PROXY
      value: http://your-proxy.com
    - name: HTTPS_PROXY
      value: http://your-proxy.com
      ...
```

In the meantime, it'd be helpful if you could confirm a few things including whether you are setting these values on your Rancher server, and what version of the driver you are using (there is no such version 1.15.0). I'd also be curious about what the value of XXXXXX was in "https://iaas.XXXXXX.oraclecloud.com" just in case its somehow related to #20 (i.e. not being subscribed to PHX).
